# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Erhan/Desktop/Koordinator/ibeV1/screens/add_change_workplace.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(648, 798)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lw_students = QtWidgets.QListWidget(Form)
        self.lw_students.setObjectName("lw_students")
        self.verticalLayout.addWidget(self.lw_students)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.lw_workplaces = QtWidgets.QListWidget(Form)
        self.lw_workplaces.setObjectName("lw_workplaces")
        self.verticalLayout_2.addWidget(self.lw_workplaces)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.le_id_number = QtWidgets.QLineEdit(Form)
        self.le_id_number.setEnabled(False)
        self.le_id_number.setObjectName("le_id_number")
        self.verticalLayout_4.addWidget(self.le_id_number)
        self.le_number = QtWidgets.QLineEdit(Form)
        self.le_number.setEnabled(False)
        self.le_number.setObjectName("le_number")
        self.verticalLayout_4.addWidget(self.le_number)
        self.le_name = QtWidgets.QLineEdit(Form)
        self.le_name.setEnabled(False)
        self.le_name.setObjectName("le_name")
        self.verticalLayout_4.addWidget(self.le_name)
        self.le_class = QtWidgets.QLineEdit(Form)
        self.le_class.setEnabled(False)
        self.le_class.setObjectName("le_class")
        self.verticalLayout_4.addWidget(self.le_class)
        self.le_old_workplace = QtWidgets.QLineEdit(Form)
        self.le_old_workplace.setEnabled(False)
        self.le_old_workplace.setObjectName("le_old_workplace")
        self.verticalLayout_4.addWidget(self.le_old_workplace)
        self.le_coordinator = QtWidgets.QLineEdit(Form)
        self.le_coordinator.setEnabled(False)
        self.le_coordinator.setObjectName("le_coordinator")
        self.verticalLayout_4.addWidget(self.le_coordinator)
        self.le_new_workplace = QtWidgets.QLineEdit(Form)
        self.le_new_workplace.setEnabled(False)
        self.le_new_workplace.setObjectName("le_new_workplace")
        self.verticalLayout_4.addWidget(self.le_new_workplace)
        self.date_starting = QtWidgets.QDateEdit(Form)
        self.date_starting.setCalendarPopup(True)
        self.date_starting.setObjectName("date_starting")
        self.verticalLayout_4.addWidget(self.date_starting)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_edit = QtWidgets.QPushButton(Form)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout_2.addWidget(self.btn_edit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_delete = QtWidgets.QPushButton(Form)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 10)
        self.horizontalLayout_2.setStretch(3, 5)
        self.horizontalLayout_2.setStretch(4, 10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 10)
        self.verticalLayout_5.setStretch(2, 5)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Öğrenciler"))
        self.label_9.setText(_translate("Form", "İşletmeler"))
        self.label_6.setText(_translate("Form", "TC kimlik No : "))
        self.label_5.setText(_translate("Form", "Numarası : "))
        self.label_3.setText(_translate("Form", "Adı Soyadı : "))
        self.label_4.setText(_translate("Form", "Sınıfı : "))
        self.label.setText(_translate("Form", "Eski İşletme : "))
        self.label_10.setText(_translate("Form", "Koordinatör : "))
        self.label_2.setText(_translate("Form", "Yeni İşletme : "))
        self.label_8.setText(_translate("Form", "Başlangıç Tarihi : "))
        self.btn_save.setText(_translate("Form", "Kaydet"))
        self.btn_edit.setText(_translate("Form", "Düzenle"))
        self.btn_delete.setText(_translate("Form", "Sil"))

